version: "3.8"
services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: shortify
      POSTGRES_USER: shortifyuser
      POSTGRES_PASSWORD: shortify@123
    ports:
      - "5432:5432"
  app:
    build: /root/external/url-shortner
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/shortify
      SPRING_DATASOURCE_USERNAME: shortifyuser
      SPRING_DATASOURCE_PASSWORD: shortify@123
    ports:
      - "8080:8080"
    depends_on:
      - postgres
