version: "3.8"
services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: shortify
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
  app:
    build: ../../AppData/Local/Temp
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/shortify
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
    ports:
      - "8080:8080"
    depends_on:
      - postgres
